/**
 * Seed data for Minimarket categories and products.
 * Prices are in Ethiopian Birr (ETB).
 */
const initialCategories = [
  {
    id: 'produce',
    name: 'Fresh Fruits & Vegetables',
    icon: '🍎',
    description: 'Farm-fresh organic fruits and vegetables delivered daily',
  },
  {
    id: 'dairy_bakery',
    name: 'Dairy, Eggs & Bakery',
    icon: '🥛',
    description: 'Fresh milk, yogurt, eggs, local bread, and injera',
  },
  {
    id: 'beverages',
    name: 'Beverages & Soft Drinks',
    icon: '🥤',
    description: 'Bottled water, sodas, juices, coffee, and tea',
  },
  {
    id: 'pantry',
    name: 'Pantry & Canned Goods',
    icon: '🥫',
    description: 'Cooking oil, rice, pasta, flour, spices, and sauces',
  },
  {
    id: 'snacks',
    name: 'Snacks & Confectionery',
    icon: '🍫',
    description: 'Biscuits, chips, chocolates, and sweets',
  },
  {
    id: 'household',
    name: 'Cleaning & Household',
    icon: '🧼',
    description: 'Detergents, soaps, paper towels, and home care items',
  },
];

const initialProducts = [
  // Produce
  {
    id: 'prod_banana',
    categoryId: 'produce',
    name: 'Fresh Bananas',
    price: 120,
    unit: '1 kg',
    description: 'Sweet, locally grown ripe bananas.',
    inStock: true,
  },
  {
    id: 'prod_tomato',
    categoryId: 'produce',
    name: 'Red Tomatoes',
    price: 90,
    unit: '1 kg',
    description: 'Juicy salad and cooking tomatoes.',
    inStock: true,
  },
  {
    id: 'prod_onion',
    categoryId: 'produce',
    name: 'Red Onions',
    price: 130,
    unit: '1 kg',
    description: 'Essential cooking red onions.',
    inStock: true,
  },
  {
    id: 'prod_potato',
    categoryId: 'produce',
    name: 'Local Potatoes',
    price: 80,
    unit: '1 kg',
    description: 'Fresh highland potatoes.',
    inStock: true,
  },
  {
    id: 'prod_orange',
    categoryId: 'produce',
    name: 'Valencia Oranges',
    price: 160,
    unit: '1 kg',
    description: 'Fresh citrus oranges rich in Vitamin C.',
    inStock: true,
  },

  // Dairy & Bakery
  {
    id: 'prod_milk_1l',
    categoryId: 'dairy_bakery',
    name: 'Pasteurized Whole Milk',
    price: 110,
    unit: '1 Liter',
    description: 'Fresh whole pasteurized milk.',
    inStock: true,
  },
  {
    id: 'prod_eggs_12',
    categoryId: 'dairy_bakery',
    name: 'Fresh Farm Eggs',
    price: 240,
    unit: '12 pcs (Dozen)',
    description: 'Grade A fresh farm eggs.',
    inStock: true,
  },
  {
    id: 'prod_injera',
    categoryId: 'dairy_bakery',
    name: 'Fresh Teff Injera',
    price: 150,
    unit: '5 pcs pack',
    description: '100% pure teff freshly baked injera.',
    inStock: true,
  },
  {
    id: 'prod_bread_toast',
    categoryId: 'dairy_bakery',
    name: 'Sliced Toast Bread',
    price: 85,
    unit: '1 loaf (500g)',
    description: 'Soft white sliced sandwich bread.',
    inStock: true,
  },
  {
    id: 'prod_butter',
    categoryId: 'dairy_bakery',
    name: 'Table Butter',
    price: 280,
    unit: '250g pack',
    description: 'Creamy unsalted table butter.',
    inStock: true,
  },

  // Beverages
  {
    id: 'prod_water_2l',
    categoryId: 'beverages',
    name: 'Natural Mineral Water',
    price: 45,
    unit: '2 Liters',
    description: 'Pure refreshing spring water.',
    inStock: true,
  },
  {
    id: 'prod_coca_cola',
    categoryId: 'beverages',
    name: 'Coca Cola Plastic Bottle',
    price: 50,
    unit: '500 ml',
    description: 'Classic chilled Coca Cola.',
    inStock: true,
  },
  {
    id: 'prod_juice_mango',
    categoryId: 'beverages',
    name: 'Mango Nectar Juice',
    price: 95,
    unit: '1 Liter',
    description: 'Rich tropical mango juice drink.',
    inStock: true,
  },
  {
    id: 'prod_coffee_beans',
    categoryId: 'beverages',
    name: 'Yirgacheffe Roast Coffee',
    price: 480,
    unit: '500g pack',
    description: 'Premium roasted Ethiopian highland coffee.',
    inStock: true,
  },

  // Pantry
  {
    id: 'prod_oil_1l',
    categoryId: 'pantry',
    name: 'Sunflower Cooking Oil',
    price: 420,
    unit: '1 Liter',
    description: 'Refined pure sunflower oil for healthy cooking.',
    inStock: true,
  },
  {
    id: 'prod_pasta',
    categoryId: 'pantry',
    name: 'Spaghetti Pasta',
    price: 75,
    unit: '500g pack',
    description: 'Quality durum wheat semolina spaghetti.',
    inStock: true,
  },
  {
    id: 'prod_rice_basmati',
    categoryId: 'pantry',
    name: 'Premium Basmati Rice',
    price: 260,
    unit: '1 kg',
    description: 'Long grain aromatic basmati rice.',
    inStock: true,
  },
  {
    id: 'prod_sugar',
    categoryId: 'pantry',
    name: 'White Cane Sugar',
    price: 140,
    unit: '1 kg',
    description: 'Pure granulated cane sugar.',
    inStock: true,
  },

  // Snacks
  {
    id: 'prod_chips_potato',
    categoryId: 'snacks',
    name: 'Crispy Potato Chips',
    price: 65,
    unit: '100g bag',
    description: 'Lightly salted golden potato crisps.',
    inStock: true,
  },
  {
    id: 'prod_chocolate_bar',
    categoryId: 'snacks',
    name: 'Milk Chocolate Bar',
    price: 90,
    unit: '80g bar',
    description: 'Smooth and creamy milk chocolate.',
    inStock: true,
  },
  {
    id: 'prod_biscuits',
    categoryId: 'snacks',
    name: 'Digestive Biscuits',
    price: 80,
    unit: '200g pack',
    description: 'Crisp whole-wheat digestive biscuits.',
    inStock: true,
  },

  // Household
  {
    id: 'prod_dish_soap',
    categoryId: 'household',
    name: 'Lemon Dishwashing Liquid',
    price: 180,
    unit: '750 ml',
    description: 'Tough on grease, gentle on hands.',
    inStock: true,
  },
  {
    id: 'prod_laundry_detergent',
    categoryId: 'household',
    name: 'Washing Powder Detergent',
    price: 320,
    unit: '1 kg bag',
    description: 'Powerful stain removal with fresh scent.',
    inStock: true,
  },
  {
    id: 'prod_toilet_paper',
    categoryId: 'household',
    name: 'Soft Toilet Rolls',
    price: 190,
    unit: '4 rolls pack',
    description: '2-ply soft and absorbent bathroom rolls.',
    inStock: true,
  },
];

module.exports = {
  initialCategories,
  initialProducts,
};
